### ISSUE TITLE
Can't get the name attribute of a switch

### ISSUE THREAD

**Issue by vincentbarbesant** [powsybl/pypowsybl#235]
* **Do you want to request a *feature* or report a *bug*?**
A feature.

* **What is the current behavior?**

This snippet :
```
topo = network.get_voltage_level_topology(voltage_level_id)
switches = topo.switches
```
returns :
```
                                        kind   open  retained  node1  node2
id                                                                         
BREUIP7_BREUI   7MARMA.1  SA.1  DISCONNECTOR  False     False      0      6
BREUIP7_BREUI   7RUEYR.1  SA.1  DISCONNECTOR   True     False      0      8
BREUIP7_BREUI   7AT762    SA.1  DISCONNECTOR  False     False      0      2
BREUIP7_BREUI   7COUPL    SA.1  DISCONNECTOR  False     False      5      0
BREUIP7_BREUI   7COUPL    SA.2  DISCONNECTOR  False     False      1      4
BREUIP7_BREUI   7MARMA.1  SA.2  DISCONNECTOR   True     False      1      6
BREUIP7_BREUI   7RUEYR.1  SA.2  DISCONNECTOR  False     False      1      8
BREUIP7_BREUI   7AT762    SA.2  DISCONNECTOR   True     False      1      2
BREUIP7_BREUI   7AT762    DJ         BREAKER  False      True      2      3
BREUIP7_BREUI   7COUPL    DJ         BREAKER  False      True      4      5
BREUIP7_BREUI   7MARMA.1  DJ         BREAKER   True      True      6      7
BREUIP7_BREUI   7RUEYR.1  DJ         BREAKER  False      True      8      9
```

* **What is the expected behavior?**
I would like to have a new column in the switches dataframe with the name attribute of the switches, which is different from the id :
`<iidm:switch id="BREUIP7_BREUI   7MARMA.1  DJ" name="BREUI   7MARMA.1  DJ" kind="BREAKER" retained="true" open="true" node1="6" node2="7"/>`

* **What is the motivation / use case for changing the behavior?**
I need this name to identify the correct switch 

* **Please tell us about your environment:**
  - PowSyBl Version: 0.9.0
  - OS Version: Windows 10

**Comment by geofjamg** [comment]
Solved by #236

**Comment by vincentbarbesant** [comment]
Installed 0.10.0 version, but still don't have access to the name of switches :
```
                                        kind   open  retained  node1  node2
id                                                                         
BREUIP7_BREUI   7MARMA.1  SA.1  DISCONNECTOR  False     False      0      6
BREUIP7_BREUI   7RUEYR.1  SA.1  DISCONNECTOR   True     False      0      8
BREUIP7_BREUI   7AT762    SA.1  DISCONNECTOR  False     False      0      2
BREUIP7_BREUI   7COUPL    SA.1  DISCONNECTOR  False     False      5      0
BREUIP7_BREUI   7COUPL    SA.2  DISCONNECTOR  False     False      1      4
BREUIP7_BREUI   7MARMA.1  SA.2  DISCONNECTOR   True     False      1      6
BREUIP7_BREUI   7RUEYR.1  SA.2  DISCONNECTOR  False     False      1      8
BREUIP7_BREUI   7AT762    SA.2  DISCONNECTOR   True     False      1      2
BREUIP7_BREUI   7AT762    DJ         BREAKER  False      True      2      3
BREUIP7_BREUI   7COUPL    DJ         BREAKER  False      True      4      5
BREUIP7_BREUI   7MARMA.1  DJ         BREAKER   True      True      6      7
BREUIP7_BREUI   7RUEYR.1  DJ         BREAKER  False      True      8      9
```
